jobs:
  give_comment:
    if: github.event.issue.state == 'open' || github.event.pull_request.state == 'open'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: master
    - continue-on-error: true
      name: Send Issue/Pull request comment
      uses: peaceiris/actions-label-commenter@v1.8.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
name: Comment
on:
  repository_dispatch:
    types: trigger-ga___label_comment.yml
