jobs:
  testBuilds:
    name: Compile jar against ${{ matrix.java-version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Prepare Java ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Make build.gradle executable
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build jar with Java ${{ matrix.java-version }}
      run: ./gradlew shadowJar
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - 8
        - 11
        - 16
      max-parallel: 4
name: Test compiling against Java 8, 11 and 16
on:
  repository_dispatch:
    types: trigger-ga___pr_build_jars.yml
